//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:01:03 PM IST 
//


package com.travis.webservices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.travis.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.travis.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaxDetails.PaxDetail }
     * 
     */
    public PaxDetails.PaxDetail createPaxDetailsPaxDetail() {
        return new PaxDetails.PaxDetail();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRS.Trip.PickupPoints }
     * 
     */
    public WsCheckAvailabilityRS.Trip.PickupPoints createWsCheckAvailabilityRSTripPickupPoints() {
        return new WsCheckAvailabilityRS.Trip.PickupPoints();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelable1XRS }
     * 
     */
    public WsIsBookingCancelable1XRS createWsIsBookingCancelable1XRS() {
        return new WsIsBookingCancelable1XRS();
    }

    /**
     * Create an instance of {@link WsRetrieveBookingRQ }
     * 
     */
    public WsRetrieveBookingRQ createWsRetrieveBookingRQ() {
        return new WsRetrieveBookingRQ();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRS.Trip.Taxes.TaxInfo }
     * 
     */
    public WsCheckAvailabilityRS.Trip.Taxes.TaxInfo createWsCheckAvailabilityRSTripTaxesTaxInfo() {
        return new WsCheckAvailabilityRS.Trip.Taxes.TaxInfo();
    }

    /**
     * Create an instance of {@link WsConfirmBookingRS }
     * 
     */
    public WsConfirmBookingRS createWsConfirmBookingRS() {
        return new WsConfirmBookingRS();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPairRS.SourceDestination.Destinations.Destination }
     * 
     */
    public WsSourceDestinationPairRS.SourceDestination.Destinations.Destination createWsSourceDestinationPairRSSourceDestinationDestinationsDestination() {
        return new WsSourceDestinationPairRS.SourceDestination.Destinations.Destination();
    }

    /**
     * Create an instance of {@link WsMakeBookingRS.BookingAmount }
     * 
     */
    public WsMakeBookingRS.BookingAmount createWsMakeBookingRSBookingAmount() {
        return new WsMakeBookingRS.BookingAmount();
    }

    /**
     * Create an instance of {@link WsGetSeatMapRS }
     * 
     */
    public WsGetSeatMapRS createWsGetSeatMapRS() {
        return new WsGetSeatMapRS();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPairRS }
     * 
     */
    public WsSourceDestinationPairRS createWsSourceDestinationPairRS() {
        return new WsSourceDestinationPairRS();
    }

    /**
     * Create an instance of {@link WsGetSeatMapRQ }
     * 
     */
    public WsGetSeatMapRQ createWsGetSeatMapRQ() {
        return new WsGetSeatMapRQ();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelable1XRQ }
     * 
     */
    public WsIsBookingCancelable1XRQ createWsIsBookingCancelable1XRQ() {
        return new WsIsBookingCancelable1XRQ();
    }

    /**
     * Create an instance of {@link WsHoldSeatRS }
     * 
     */
    public WsHoldSeatRS createWsHoldSeatRS() {
        return new WsHoldSeatRS();
    }

    /**
     * Create an instance of {@link WsGetBalanceRQ }
     * 
     */
    public WsGetBalanceRQ createWsGetBalanceRQ() {
        return new WsGetBalanceRQ();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPairRS.SourceDestination.Destinations }
     * 
     */
    public WsSourceDestinationPairRS.SourceDestination.Destinations createWsSourceDestinationPairRSSourceDestinationDestinations() {
        return new WsSourceDestinationPairRS.SourceDestination.Destinations();
    }

    /**
     * Create an instance of {@link WsGetCityRS }
     * 
     */
    public WsGetCityRS createWsGetCityRS() {
        return new WsGetCityRS();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRS }
     * 
     */
    public WsCheckAvailabilityRS createWsCheckAvailabilityRS() {
        return new WsCheckAvailabilityRS();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRQ }
     * 
     */
    public WsCheckAvailabilityRQ createWsCheckAvailabilityRQ() {
        return new WsCheckAvailabilityRQ();
    }

    /**
     * Create an instance of {@link WsGetBalanceRS }
     * 
     */
    public WsGetBalanceRS createWsGetBalanceRS() {
        return new WsGetBalanceRS();
    }

    /**
     * Create an instance of {@link WsRetrieveBookingRS }
     * 
     */
    public WsRetrieveBookingRS createWsRetrieveBookingRS() {
        return new WsRetrieveBookingRS();
    }

    /**
     * Create an instance of {@link WsGetBookingDetailsRQ }
     * 
     */
    public WsGetBookingDetailsRQ createWsGetBookingDetailsRQ() {
        return new WsGetBookingDetailsRQ();
    }

    /**
     * Create an instance of {@link WsGetCityRS.City }
     * 
     */
    public WsGetCityRS.City createWsGetCityRSCity() {
        return new WsGetCityRS.City();
    }

    /**
     * Create an instance of {@link WsCancelBooking1XRS }
     * 
     */
    public WsCancelBooking1XRS createWsCancelBooking1XRS() {
        return new WsCancelBooking1XRS();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRS.Trip.Taxes }
     * 
     */
    public WsCheckAvailabilityRS.Trip.Taxes createWsCheckAvailabilityRSTripTaxes() {
        return new WsCheckAvailabilityRS.Trip.Taxes();
    }

    /**
     * Create an instance of {@link WsGetBookingDetailsRS }
     * 
     */
    public WsGetBookingDetailsRS createWsGetBookingDetailsRS() {
        return new WsGetBookingDetailsRS();
    }

    /**
     * Create an instance of {@link WsHoldSeatRQ }
     * 
     */
    public WsHoldSeatRQ createWsHoldSeatRQ() {
        return new WsHoldSeatRQ();
    }

    /**
     * Create an instance of {@link WsConfirmBookingRQ }
     * 
     */
    public WsConfirmBookingRQ createWsConfirmBookingRQ() {
        return new WsConfirmBookingRQ();
    }

    /**
     * Create an instance of {@link WsCancelBooking1XRQ }
     * 
     */
    public WsCancelBooking1XRQ createWsCancelBooking1XRQ() {
        return new WsCancelBooking1XRQ();
    }

    /**
     * Create an instance of {@link WsMakeBookingRQ.ContactDetails }
     * 
     */
    public WsMakeBookingRQ.ContactDetails createWsMakeBookingRQContactDetails() {
        return new WsMakeBookingRQ.ContactDetails();
    }

    /**
     * Create an instance of {@link PaxDetails }
     * 
     */
    public PaxDetails createPaxDetails() {
        return new PaxDetails();
    }

    /**
     * Create an instance of {@link WsCancelBookingRQ }
     * 
     */
    public WsCancelBookingRQ createWsCancelBookingRQ() {
        return new WsCancelBookingRQ();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPairRS.SourceDestination }
     * 
     */
    public WsSourceDestinationPairRS.SourceDestination createWsSourceDestinationPairRSSourceDestination() {
        return new WsSourceDestinationPairRS.SourceDestination();
    }

    /**
     * Create an instance of {@link WsGetSourceDestinationPairRQ }
     * 
     */
    public WsGetSourceDestinationPairRQ createWsGetSourceDestinationPairRQ() {
        return new WsGetSourceDestinationPairRQ();
    }

    /**
     * Create an instance of {@link WsMakeBookingRQ }
     * 
     */
    public WsMakeBookingRQ createWsMakeBookingRQ() {
        return new WsMakeBookingRQ();
    }

    /**
     * Create an instance of {@link SeatStatus }
     * 
     */
    public SeatStatus createSeatStatus() {
        return new SeatStatus();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPairRS.SourceDestination.Origin }
     * 
     */
    public WsSourceDestinationPairRS.SourceDestination.Origin createWsSourceDestinationPairRSSourceDestinationOrigin() {
        return new WsSourceDestinationPairRS.SourceDestination.Origin();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRS.Trip }
     * 
     */
    public WsCheckAvailabilityRS.Trip createWsCheckAvailabilityRSTrip() {
        return new WsCheckAvailabilityRS.Trip();
    }

    /**
     * Create an instance of {@link WsGetCityRQ }
     * 
     */
    public WsGetCityRQ createWsGetCityRQ() {
        return new WsGetCityRQ();
    }

    /**
     * Create an instance of {@link WsGetSeatMapRS.TripSeat }
     * 
     */
    public WsGetSeatMapRS.TripSeat createWsGetSeatMapRSTripSeat() {
        return new WsGetSeatMapRS.TripSeat();
    }

    /**
     * Create an instance of {@link WsCancelBookingRS }
     * 
     */
    public WsCancelBookingRS createWsCancelBookingRS() {
        return new WsCancelBookingRS();
    }

    /**
     * Create an instance of {@link WsHoldSeatRQ.Seats }
     * 
     */
    public WsHoldSeatRQ.Seats createWsHoldSeatRQSeats() {
        return new WsHoldSeatRQ.Seats();
    }

    /**
     * Create an instance of {@link WsCancelBooking1XRQ.Seat }
     * 
     */
    public WsCancelBooking1XRQ.Seat createWsCancelBooking1XRQSeat() {
        return new WsCancelBooking1XRQ.Seat();
    }

    /**
     * Create an instance of {@link PickupPoint }
     * 
     */
    public PickupPoint createPickupPoint() {
        return new PickupPoint();
    }

    /**
     * Create an instance of {@link WsMakeBookingRS }
     * 
     */
    public WsMakeBookingRS createWsMakeBookingRS() {
        return new WsMakeBookingRS();
    }

    /**
     * Create an instance of {@link WsAuthenticate }
     * 
     */
    public WsAuthenticate createWsAuthenticate() {
        return new WsAuthenticate();
    }

    /**
     * Create an instance of {@link PaymentDetails }
     * 
     */
    public PaymentDetails createPaymentDetails() {
        return new PaymentDetails();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelableRS }
     * 
     */
    public WsIsBookingCancelableRS createWsIsBookingCancelableRS() {
        return new WsIsBookingCancelableRS();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityRS.City }
     * 
     */
    public WsCheckAvailabilityRS.City createWsCheckAvailabilityRSCity() {
        return new WsCheckAvailabilityRS.City();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelableRQ }
     * 
     */
    public WsIsBookingCancelableRQ createWsIsBookingCancelableRQ() {
        return new WsIsBookingCancelableRQ();
    }

}
