//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:01:03 PM IST 
//


package com.travis.webservices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * This is class is used to send the response with following parameters.
 * 
 * <p>Java class for wsCheckAvailabilityRS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsCheckAvailabilityRS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="city" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="markForDelete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="stateId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="countryId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="lalitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trip" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="adultFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="tripId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="tripTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="arrivalTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="taxPercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fromCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="toCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="seatFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sleeperFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="seatType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pickupPoint" type="{http://travis.com/webservices}pickupPoint" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="taxes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="taxInfo" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="taxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="taxType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="tripType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="busType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serviceProviderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="tripName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pickupPoints" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="pickupPoint" type="{http://travis.com/webservices}pickupPoint" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="specificId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serviceDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cancellationPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsCheckAvailabilityRS", propOrder = {
    "error",
    "city",
    "errorCode",
    "trip"
})
public class WsCheckAvailabilityRS {

    protected String error;
    protected WsCheckAvailabilityRS.City city;
    protected String errorCode;
    protected List<WsCheckAvailabilityRS.Trip> trip;
    @XmlAttribute(required = true)
    protected long group;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link WsCheckAvailabilityRS.City }
     *     
     */
    public WsCheckAvailabilityRS.City getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsCheckAvailabilityRS.City }
     *     
     */
    public void setCity(WsCheckAvailabilityRS.City value) {
        this.city = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the trip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsCheckAvailabilityRS.Trip }
     * 
     * 
     */
    public List<WsCheckAvailabilityRS.Trip> getTrip() {
        if (trip == null) {
            trip = new ArrayList<WsCheckAvailabilityRS.Trip>();
        }
        return this.trip;
    }

    /**
     * Gets the value of the group property.
     * 
     */
    public long getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     */
    public void setGroup(long value) {
        this.group = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="markForDelete" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="stateId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="countryId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="lalitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "description"
    })
    public static class City {

        protected String name;
        protected String description;
        @XmlAttribute(required = true)
        protected long id;
        @XmlAttribute(required = true)
        protected boolean markForDelete;
        @XmlAttribute(required = true)
        protected long stateId;
        @XmlAttribute(required = true)
        protected long countryId;
        @XmlAttribute(required = true)
        protected double longitude;
        @XmlAttribute(required = true)
        protected double lalitude;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the markForDelete property.
         * 
         */
        public boolean isMarkForDelete() {
            return markForDelete;
        }

        /**
         * Sets the value of the markForDelete property.
         * 
         */
        public void setMarkForDelete(boolean value) {
            this.markForDelete = value;
        }

        /**
         * Gets the value of the stateId property.
         * 
         */
        public long getStateId() {
            return stateId;
        }

        /**
         * Sets the value of the stateId property.
         * 
         */
        public void setStateId(long value) {
            this.stateId = value;
        }

        /**
         * Gets the value of the countryId property.
         * 
         */
        public long getCountryId() {
            return countryId;
        }

        /**
         * Sets the value of the countryId property.
         * 
         */
        public void setCountryId(long value) {
            this.countryId = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         */
        public double getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         */
        public void setLongitude(double value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the lalitude property.
         * 
         */
        public double getLalitude() {
            return lalitude;
        }

        /**
         * Sets the value of the lalitude property.
         * 
         */
        public void setLalitude(double value) {
            this.lalitude = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="adultFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="tripId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="tripTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="arrivalTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="taxPercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fromCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="toCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="seatFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sleeperFare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="seatType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pickupPoint" type="{http://travis.com/webservices}pickupPoint" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="taxes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="taxInfo" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="taxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="taxType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="tripType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="busType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="serviceProviderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="tripName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pickupPoints" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="pickupPoint" type="{http://travis.com/webservices}pickupPoint" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="specificId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="serviceDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cancellationPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adultFare",
        "tripId",
        "tripTime",
        "arrivalTime",
        "taxPercent",
        "fromCity",
        "toCity",
        "seatFare",
        "sleeperFare",
        "seatType",
        "pickupPoint",
        "taxes",
        "tripType",
        "busType",
        "serviceProviderName",
        "tripName",
        "pickupPoints",
        "groupName",
        "specificId",
        "priority",
        "serviceDetails",
        "cancellationPolicy"
    })
    public static class Trip {

        protected String adultFare;
        protected String tripId;
        protected String tripTime;
        protected String arrivalTime;
        protected String taxPercent;
        protected String fromCity;
        protected String toCity;
        protected String seatFare;
        protected String sleeperFare;
        protected String seatType;
        protected List<PickupPoint> pickupPoint;
        protected WsCheckAvailabilityRS.Trip.Taxes taxes;
        protected String tripType;
        protected String busType;
        protected String serviceProviderName;
        protected String tripName;
        protected WsCheckAvailabilityRS.Trip.PickupPoints pickupPoints;
        protected String groupName;
        protected String specificId;
        protected String priority;
        protected String serviceDetails;
        protected String cancellationPolicy;

        /**
         * Gets the value of the adultFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdultFare() {
            return adultFare;
        }

        /**
         * Sets the value of the adultFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdultFare(String value) {
            this.adultFare = value;
        }

        /**
         * Gets the value of the tripId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTripId() {
            return tripId;
        }

        /**
         * Sets the value of the tripId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTripId(String value) {
            this.tripId = value;
        }

        /**
         * Gets the value of the tripTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTripTime() {
            return tripTime;
        }

        /**
         * Sets the value of the tripTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTripTime(String value) {
            this.tripTime = value;
        }

        /**
         * Gets the value of the arrivalTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrivalTime() {
            return arrivalTime;
        }

        /**
         * Sets the value of the arrivalTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrivalTime(String value) {
            this.arrivalTime = value;
        }

        /**
         * Gets the value of the taxPercent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxPercent() {
            return taxPercent;
        }

        /**
         * Sets the value of the taxPercent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxPercent(String value) {
            this.taxPercent = value;
        }

        /**
         * Gets the value of the fromCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromCity() {
            return fromCity;
        }

        /**
         * Sets the value of the fromCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromCity(String value) {
            this.fromCity = value;
        }

        /**
         * Gets the value of the toCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToCity() {
            return toCity;
        }

        /**
         * Sets the value of the toCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToCity(String value) {
            this.toCity = value;
        }

        /**
         * Gets the value of the seatFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeatFare() {
            return seatFare;
        }

        /**
         * Sets the value of the seatFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeatFare(String value) {
            this.seatFare = value;
        }

        /**
         * Gets the value of the sleeperFare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSleeperFare() {
            return sleeperFare;
        }

        /**
         * Sets the value of the sleeperFare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSleeperFare(String value) {
            this.sleeperFare = value;
        }

        /**
         * Gets the value of the seatType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeatType() {
            return seatType;
        }

        /**
         * Sets the value of the seatType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeatType(String value) {
            this.seatType = value;
        }

        /**
         * Gets the value of the pickupPoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pickupPoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPickupPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PickupPoint }
         * 
         * 
         */
        public List<PickupPoint> getPickupPoint() {
            if (pickupPoint == null) {
                pickupPoint = new ArrayList<PickupPoint>();
            }
            return this.pickupPoint;
        }

        /**
         * Gets the value of the taxes property.
         * 
         * @return
         *     possible object is
         *     {@link WsCheckAvailabilityRS.Trip.Taxes }
         *     
         */
        public WsCheckAvailabilityRS.Trip.Taxes getTaxes() {
            return taxes;
        }

        /**
         * Sets the value of the taxes property.
         * 
         * @param value
         *     allowed object is
         *     {@link WsCheckAvailabilityRS.Trip.Taxes }
         *     
         */
        public void setTaxes(WsCheckAvailabilityRS.Trip.Taxes value) {
            this.taxes = value;
        }

        /**
         * Gets the value of the tripType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTripType() {
            return tripType;
        }

        /**
         * Sets the value of the tripType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTripType(String value) {
            this.tripType = value;
        }

        /**
         * Gets the value of the busType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBusType() {
            return busType;
        }

        /**
         * Sets the value of the busType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBusType(String value) {
            this.busType = value;
        }

        /**
         * Gets the value of the serviceProviderName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceProviderName() {
            return serviceProviderName;
        }

        /**
         * Sets the value of the serviceProviderName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceProviderName(String value) {
            this.serviceProviderName = value;
        }

        /**
         * Gets the value of the tripName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTripName() {
            return tripName;
        }

        /**
         * Sets the value of the tripName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTripName(String value) {
            this.tripName = value;
        }

        /**
         * Gets the value of the pickupPoints property.
         * 
         * @return
         *     possible object is
         *     {@link WsCheckAvailabilityRS.Trip.PickupPoints }
         *     
         */
        public WsCheckAvailabilityRS.Trip.PickupPoints getPickupPoints() {
            return pickupPoints;
        }

        /**
         * Sets the value of the pickupPoints property.
         * 
         * @param value
         *     allowed object is
         *     {@link WsCheckAvailabilityRS.Trip.PickupPoints }
         *     
         */
        public void setPickupPoints(WsCheckAvailabilityRS.Trip.PickupPoints value) {
            this.pickupPoints = value;
        }

        /**
         * Gets the value of the groupName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupName() {
            return groupName;
        }

        /**
         * Sets the value of the groupName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupName(String value) {
            this.groupName = value;
        }

        /**
         * Gets the value of the specificId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecificId() {
            return specificId;
        }

        /**
         * Sets the value of the specificId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecificId(String value) {
            this.specificId = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the serviceDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceDetails() {
            return serviceDetails;
        }

        /**
         * Sets the value of the serviceDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceDetails(String value) {
            this.serviceDetails = value;
        }

        /**
         * Gets the value of the cancellationPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCancellationPolicy() {
            return cancellationPolicy;
        }

        /**
         * Sets the value of the cancellationPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCancellationPolicy(String value) {
            this.cancellationPolicy = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="pickupPoint" type="{http://travis.com/webservices}pickupPoint" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pickupPoint"
        })
        public static class PickupPoints {

            protected List<PickupPoint> pickupPoint;

            /**
             * Gets the value of the pickupPoint property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the pickupPoint property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPickupPoint().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PickupPoint }
             * 
             * 
             */
            public List<PickupPoint> getPickupPoint() {
                if (pickupPoint == null) {
                    pickupPoint = new ArrayList<PickupPoint>();
                }
                return this.pickupPoint;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="taxInfo" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="taxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="taxType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxInfo"
        })
        public static class Taxes {

            protected WsCheckAvailabilityRS.Trip.Taxes.TaxInfo taxInfo;

            /**
             * Gets the value of the taxInfo property.
             * 
             * @return
             *     possible object is
             *     {@link WsCheckAvailabilityRS.Trip.Taxes.TaxInfo }
             *     
             */
            public WsCheckAvailabilityRS.Trip.Taxes.TaxInfo getTaxInfo() {
                return taxInfo;
            }

            /**
             * Sets the value of the taxInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link WsCheckAvailabilityRS.Trip.Taxes.TaxInfo }
             *     
             */
            public void setTaxInfo(WsCheckAvailabilityRS.Trip.Taxes.TaxInfo value) {
                this.taxInfo = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="taxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="taxType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "taxAmount",
                "taxType"
            })
            public static class TaxInfo {

                protected String taxAmount;
                protected String taxType;

                /**
                 * Gets the value of the taxAmount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTaxAmount() {
                    return taxAmount;
                }

                /**
                 * Sets the value of the taxAmount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTaxAmount(String value) {
                    this.taxAmount = value;
                }

                /**
                 * Gets the value of the taxType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTaxType() {
                    return taxType;
                }

                /**
                 * Sets the value of the taxType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTaxType(String value) {
                    this.taxType = value;
                }

            }

        }

    }

}
