//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:01:03 PM IST 
//


package com.travis.webservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsMakeBookingRS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsMakeBookingRS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pnr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="externalPnr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vendorPnr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromStop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toStop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProvider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="journeyTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pickupPoint" type="{http://travis.com/webservices}pickupPoint" minOccurs="0"/>
 *         &lt;element name="paxDetails" type="{http://travis.com/webservices}paxDetails" minOccurs="0"/>
 *         &lt;element name="bookingAmount" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="taxes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="termsAndCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancellationPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsMakeBookingRS", propOrder = {
    "pnr",
    "externalPnr",
    "vendorPnr",
    "fromStop",
    "toStop",
    "serviceProvider",
    "journeyTime",
    "pickupPoint",
    "paxDetails",
    "bookingAmount",
    "error",
    "errorCode",
    "termsAndCondition",
    "cancellationPolicy"
})
public class WsMakeBookingRS {

    protected String pnr;
    protected String externalPnr;
    protected String vendorPnr;
    protected String fromStop;
    protected String toStop;
    protected String serviceProvider;
    protected String journeyTime;
    protected PickupPoint pickupPoint;
    protected PaxDetails paxDetails;
    protected WsMakeBookingRS.BookingAmount bookingAmount;
    protected String error;
    protected String errorCode;
    protected String termsAndCondition;
    protected String cancellationPolicy;

    /**
     * Gets the value of the pnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * Sets the value of the pnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnr(String value) {
        this.pnr = value;
    }

    /**
     * Gets the value of the externalPnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalPnr() {
        return externalPnr;
    }

    /**
     * Sets the value of the externalPnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalPnr(String value) {
        this.externalPnr = value;
    }

    /**
     * Gets the value of the vendorPnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorPnr() {
        return vendorPnr;
    }

    /**
     * Sets the value of the vendorPnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorPnr(String value) {
        this.vendorPnr = value;
    }

    /**
     * Gets the value of the fromStop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromStop() {
        return fromStop;
    }

    /**
     * Sets the value of the fromStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromStop(String value) {
        this.fromStop = value;
    }

    /**
     * Gets the value of the toStop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToStop() {
        return toStop;
    }

    /**
     * Sets the value of the toStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToStop(String value) {
        this.toStop = value;
    }

    /**
     * Gets the value of the serviceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProvider(String value) {
        this.serviceProvider = value;
    }

    /**
     * Gets the value of the journeyTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJourneyTime() {
        return journeyTime;
    }

    /**
     * Sets the value of the journeyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJourneyTime(String value) {
        this.journeyTime = value;
    }

    /**
     * Gets the value of the pickupPoint property.
     * 
     * @return
     *     possible object is
     *     {@link PickupPoint }
     *     
     */
    public PickupPoint getPickupPoint() {
        return pickupPoint;
    }

    /**
     * Sets the value of the pickupPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupPoint }
     *     
     */
    public void setPickupPoint(PickupPoint value) {
        this.pickupPoint = value;
    }

    /**
     * Gets the value of the paxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PaxDetails }
     *     
     */
    public PaxDetails getPaxDetails() {
        return paxDetails;
    }

    /**
     * Sets the value of the paxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxDetails }
     *     
     */
    public void setPaxDetails(PaxDetails value) {
        this.paxDetails = value;
    }

    /**
     * Gets the value of the bookingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link WsMakeBookingRS.BookingAmount }
     *     
     */
    public WsMakeBookingRS.BookingAmount getBookingAmount() {
        return bookingAmount;
    }

    /**
     * Sets the value of the bookingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsMakeBookingRS.BookingAmount }
     *     
     */
    public void setBookingAmount(WsMakeBookingRS.BookingAmount value) {
        this.bookingAmount = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the termsAndCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsAndCondition() {
        return termsAndCondition;
    }

    /**
     * Sets the value of the termsAndCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsAndCondition(String value) {
        this.termsAndCondition = value;
    }

    /**
     * Gets the value of the cancellationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationPolicy() {
        return cancellationPolicy;
    }

    /**
     * Sets the value of the cancellationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationPolicy(String value) {
        this.cancellationPolicy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fare" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="taxes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fare",
        "taxes"
    })
    public static class BookingAmount {

        protected String fare;
        protected String taxes;

        /**
         * Gets the value of the fare property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFare() {
            return fare;
        }

        /**
         * Sets the value of the fare property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFare(String value) {
            this.fare = value;
        }

        /**
         * Gets the value of the taxes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxes() {
            return taxes;
        }

        /**
         * Sets the value of the taxes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxes(String value) {
            this.taxes = value;
        }

    }

}
