//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 06:43:41 PM IST 
//


package com.mmt.hotel.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mmt.services.product.hotel.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Promotion_QNAME = new QName("", "Promotion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mmt.services.product.hotel.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate.GuestCounts }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate.GuestCounts createMMTHotelSearchRequestSearchCriteriaCriterionRoomStayCandidatesRoomStayCandidateGuestCounts() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate.GuestCounts();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.PromotionReferenceCodes }
     * 
     */
    public MMTHotelSearchRequest.PromotionReferenceCodes createMMTHotelSearchRequestPromotionReferenceCodes() {
        return new MMTHotelSearchRequest.PromotionReferenceCodes();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate.GuestCounts.GuestCount }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate.GuestCounts.GuestCount createMMTHotelSearchRequestSearchCriteriaCriterionRoomStayCandidatesRoomStayCandidateGuestCountsGuestCount() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate.GuestCounts.GuestCount();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.POS.Source }
     * 
     */
    public MMTHotelSearchRequest.POS.Source createMMTHotelSearchRequestPOSSource() {
        return new MMTHotelSearchRequest.POS.Source();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.StayDateRanges }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.StayDateRanges createMMTHotelSearchRequestSearchCriteriaCriterionStayDateRanges() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.StayDateRanges();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.POS.Requestor }
     * 
     */
    public MMTHotelSearchRequest.POS.Requestor createMMTHotelSearchRequestPOSRequestor() {
        return new MMTHotelSearchRequest.POS.Requestor();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria createMMTHotelSearchRequestSearchCriteria() {
        return new MMTHotelSearchRequest.SearchCriteria();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.Area }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.Area createMMTHotelSearchRequestSearchCriteriaCriterionArea() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.Area();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion createMMTHotelSearchRequestSearchCriteriaCriterion() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.PromotionReferenceCodes.PromotionReferenceCode }
     * 
     */
    public MMTHotelSearchRequest.PromotionReferenceCodes.PromotionReferenceCode createMMTHotelSearchRequestPromotionReferenceCodesPromotionReferenceCode() {
        return new MMTHotelSearchRequest.PromotionReferenceCodes.PromotionReferenceCode();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate createMMTHotelSearchRequestSearchCriteriaCriterionRoomStayCandidatesRoomStayCandidate() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates.RoomStayCandidate();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.StayDateRanges.StayDateRange }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.StayDateRanges.StayDateRange createMMTHotelSearchRequestSearchCriteriaCriterionStayDateRangesStayDateRange() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.StayDateRanges.StayDateRange();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.ResultTransformer }
     * 
     */
    public MMTHotelSearchRequest.ResultTransformer createMMTHotelSearchRequestResultTransformer() {
        return new MMTHotelSearchRequest.ResultTransformer();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.POS }
     * 
     */
    public MMTHotelSearchRequest.POS createMMTHotelSearchRequestPOS() {
        return new MMTHotelSearchRequest.POS();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates }
     * 
     */
    public MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates createMMTHotelSearchRequestSearchCriteriaCriterionRoomStayCandidates() {
        return new MMTHotelSearchRequest.SearchCriteria.Criterion.RoomStayCandidates();
    }

    /**
     * Create an instance of {@link MMTHotelSearchRequest }
     * 
     */
    public MMTHotelSearchRequest createMMTHotelSearchRequest() {
        return new MMTHotelSearchRequest();
    }
    
    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel createMMTHotelSearchResponseHotelSearchResultsHotelsHotel() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults createMMTHotelSearchResponseHotelSearchResults() {
        return new MMTHotelSearchResponse.HotelSearchResults();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.POS }
     * 
     */
    public MMTHotelSearchResponse.POS createMMTHotelSearchResponsePOS() {
        return new MMTHotelSearchResponse.POS();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.MealPlans }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.MealPlans createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlansRatePlanMealPlans() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.MealPlans();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.Inclusions.Inclusion }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.Inclusions.Inclusion createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlansRatePlanInclusionsInclusion() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.Inclusions.Inclusion();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRateRoomTariffs() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff.Tariffs }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff.Tariffs createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRateRoomTariffsRoomTariffTariffs() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff.Tariffs();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRate() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.POS.Source }
     * 
     */
    public MMTHotelSearchResponse.POS.Source createMMTHotelSearchResponsePOSSource() {
        return new MMTHotelSearchResponse.POS.Source();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff.Tariffs.Tariff }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff.Tariffs.Tariff createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRateRoomTariffsRoomTariffTariffsTariff() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff.Tariffs.Tariff();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet.FacetValues.FacetValue }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet.FacetValues.FacetValue createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoFacetsFacetFacetValuesFacetValue() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet.FacetValues.FacetValue();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRate() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.PromotionReferences }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.PromotionReferences createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRatePromotionReferences() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.PromotionReferences();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse }
     * 
     */
    public MMTHotelSearchResponse createMMTHotelSearchResponse() {
        return new MMTHotelSearchResponse();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomTypes.RoomType }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomTypes.RoomType createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomTypesRoomType() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomTypes.RoomType();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.ResponseCode }
     * 
     */
    public MMTHotelSearchResponse.ResponseCode createMMTHotelSearchResponseResponseCode() {
        return new MMTHotelSearchResponse.ResponseCode();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoFacets() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate createMMTHotelSearchResponseHotelSearchResultsHotelsHotelLowestRate() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.Inclusions }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.Inclusions createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlansRatePlanInclusions() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.Inclusions();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRates() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.MediaList }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.MediaList createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoMediaList() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.MediaList();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.POS.Requestor }
     * 
     */
    public MMTHotelSearchResponse.POS.Requestor createMMTHotelSearchResponsePOSRequestor() {
        return new MMTHotelSearchResponse.POS.Requestor();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoFacetsFacet() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomTypes }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomTypes createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomTypes() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomTypes();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.CancelPenalties.CancelPenalty }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.CancelPenalties.CancelPenalty createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRateCancelPenaltiesCancelPenalty() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.CancelPenalties.CancelPenalty();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels createMMTHotelSearchResponseHotelSearchResultsHotels() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.MealPlans.MealPlan }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.MealPlans.MealPlan createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlansRatePlanMealPlansMealPlan() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.MealPlans.MealPlan();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createPromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet.FacetValues }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet.FacetValues createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoFacetsFacetFacetValues() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Facets.Facet.FacetValues();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlans() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate.LowestRate }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate.LowestRate1 createMMTHotelSearchResponseHotelSearchResultsHotelsHotelLowestRateLowestRate() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate.LowestRate1();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.MediaList.Media }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.MediaList.Media createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoMediaListMedia() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.MediaList.Media();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStays() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfo() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRateRoomTariffsRoomTariff() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.RoomTariffs.RoomTariff();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Promotions }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Promotions createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoPromotions() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.Promotions();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.PaymentModes }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.PaymentModes createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlansRatePlanPaymentModes() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan.PaymentModes();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStay() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.CancelPenalties }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.CancelPenalties createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRoomRatesRoomRateRateCancelPenalties() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RoomRates.RoomRate.Rate.CancelPenalties();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan createMMTHotelSearchResponseHotelSearchResultsHotelsHotelPropertyInfoRoomStaysRoomStayRatePlansRatePlan() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.PropertyInfo.RoomStays.RoomStay.RatePlans.RatePlan();
    }

    /**
     * Create an instance of {@link MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate.DiscountedLowestRate }
     * 
     */
    public MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate.DiscountedLowestRate createMMTHotelSearchResponseHotelSearchResultsHotelsHotelLowestRateDiscountedLowestRate() {
        return new MMTHotelSearchResponse.HotelSearchResults.Hotels.Hotel.LowestRate.DiscountedLowestRate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Promotion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Promotion")
    public JAXBElement<Promotion> createPromotion(Promotion value) {
        return new JAXBElement<Promotion>(_Promotion_QNAME, Promotion.class, null, value);
    }

}
