//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 06:40:36 PM IST 
//


package com.mmt.hotel.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="TNCLink" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="promoType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="promoLevel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="priceSlasher" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
public class Promotion {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "TNCLink")
    protected String tncLink;
    @XmlAttribute
    protected String promoType;
    @XmlAttribute
    protected String promoLevel;
    @XmlAttribute
    protected String priceSlasher;
    @XmlAttribute
    protected String code;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the tncLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTNCLink() {
        return tncLink;
    }

    /**
     * Sets the value of the tncLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTNCLink(String value) {
        this.tncLink = value;
    }

    /**
     * Gets the value of the promoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoType() {
        return promoType;
    }

    /**
     * Sets the value of the promoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoType(String value) {
        this.promoType = value;
    }

    /**
     * Gets the value of the promoLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromoLevel() {
        return promoLevel;
    }

    /**
     * Sets the value of the promoLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromoLevel(String value) {
        this.promoLevel = value;
    }

    /**
     * Gets the value of the priceSlasher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceSlasher() {
        return priceSlasher;
    }

    /**
     * Sets the value of the priceSlasher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceSlasher(String value) {
        this.priceSlasher = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
