//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:01:03 PM IST 
//


package com.travis.webservices.wsticketvala.wsticketvala;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.travis.webservices.wsticketvala.wsticketvala package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.travis.webservices.wsticketvala.wsticketvala
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WsCancelBooking }
     * 
     */
    public WsCancelBooking createWsCancelBooking() {
        return new WsCancelBooking();
    }

    /**
     * Create an instance of {@link WsCheckBooking }
     * 
     */
    public WsCheckBooking createWsCheckBooking() {
        return new WsCheckBooking();
    }

    /**
     * Create an instance of {@link WsCheckAvailability1X }
     * 
     */
    public WsCheckAvailability1X createWsCheckAvailability1X() {
        return new WsCheckAvailability1X();
    }

    /**
     * Create an instance of {@link WsTempBookingResponse }
     * 
     */
    public WsTempBookingResponse createWsTempBookingResponse() {
        return new WsTempBookingResponse();
    }

    /**
     * Create an instance of {@link WsRetrieveBookingResponse }
     * 
     */
    public WsRetrieveBookingResponse createWsRetrieveBookingResponse() {
        return new WsRetrieveBookingResponse();
    }

    /**
     * Create an instance of {@link WsGetCityResponse }
     * 
     */
    public WsGetCityResponse createWsGetCityResponse() {
        return new WsGetCityResponse();
    }

    /**
     * Create an instance of {@link WsGetBookingDetails }
     * 
     */
    public WsGetBookingDetails createWsGetBookingDetails() {
        return new WsGetBookingDetails();
    }

    /**
     * Create an instance of {@link WsCheckAvailability }
     * 
     */
    public WsCheckAvailability createWsCheckAvailability() {
        return new WsCheckAvailability();
    }

    /**
     * Create an instance of {@link WsGetSeatMap }
     * 
     */
    public WsGetSeatMap createWsGetSeatMap() {
        return new WsGetSeatMap();
    }

    /**
     * Create an instance of {@link WsCancelBooking1XResponse }
     * 
     */
    public WsCancelBooking1XResponse createWsCancelBooking1XResponse() {
        return new WsCancelBooking1XResponse();
    }

    /**
     * Create an instance of {@link WsConfirmBooking }
     * 
     */
    public WsConfirmBooking createWsConfirmBooking() {
        return new WsConfirmBooking();
    }

    /**
     * Create an instance of {@link WsMakeBooking }
     * 
     */
    public WsMakeBooking createWsMakeBooking() {
        return new WsMakeBooking();
    }

    /**
     * Create an instance of {@link WsGetBalance }
     * 
     */
    public WsGetBalance createWsGetBalance() {
        return new WsGetBalance();
    }

    /**
     * Create an instance of {@link WsCancelBooking1X }
     * 
     */
    public WsCancelBooking1X createWsCancelBooking1X() {
        return new WsCancelBooking1X();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelable }
     * 
     */
    public WsIsBookingCancelable createWsIsBookingCancelable() {
        return new WsIsBookingCancelable();
    }

    /**
     * Create an instance of {@link WsTempBooking }
     * 
     */
    public WsTempBooking createWsTempBooking() {
        return new WsTempBooking();
    }

    /**
     * Create an instance of {@link WsRetrieveBooking }
     * 
     */
    public WsRetrieveBooking createWsRetrieveBooking() {
        return new WsRetrieveBooking();
    }

    /**
     * Create an instance of {@link WsCheckAvailability1XResponse }
     * 
     */
    public WsCheckAvailability1XResponse createWsCheckAvailability1XResponse() {
        return new WsCheckAvailability1XResponse();
    }

    /**
     * Create an instance of {@link WsHoldSeatResponse }
     * 
     */
    public WsHoldSeatResponse createWsHoldSeatResponse() {
        return new WsHoldSeatResponse();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelableResponse }
     * 
     */
    public WsIsBookingCancelableResponse createWsIsBookingCancelableResponse() {
        return new WsIsBookingCancelableResponse();
    }

    /**
     * Create an instance of {@link WsMakeBookingResponse }
     * 
     */
    public WsMakeBookingResponse createWsMakeBookingResponse() {
        return new WsMakeBookingResponse();
    }

    /**
     * Create an instance of {@link WsHoldSeat }
     * 
     */
    public WsHoldSeat createWsHoldSeat() {
        return new WsHoldSeat();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelable1X }
     * 
     */
    public WsIsBookingCancelable1X createWsIsBookingCancelable1X() {
        return new WsIsBookingCancelable1X();
    }

    /**
     * Create an instance of {@link WsGetBookingDetailsResponse }
     * 
     */
    public WsGetBookingDetailsResponse createWsGetBookingDetailsResponse() {
        return new WsGetBookingDetailsResponse();
    }

    /**
     * Create an instance of {@link WsGetBalanceResponse }
     * 
     */
    public WsGetBalanceResponse createWsGetBalanceResponse() {
        return new WsGetBalanceResponse();
    }

    /**
     * Create an instance of {@link WsCheckAvailabilityResponse }
     * 
     */
    public WsCheckAvailabilityResponse createWsCheckAvailabilityResponse() {
        return new WsCheckAvailabilityResponse();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPairResponse }
     * 
     */
    public WsSourceDestinationPairResponse createWsSourceDestinationPairResponse() {
        return new WsSourceDestinationPairResponse();
    }

    /**
     * Create an instance of {@link WsCancelBookingResponse }
     * 
     */
    public WsCancelBookingResponse createWsCancelBookingResponse() {
        return new WsCancelBookingResponse();
    }

    /**
     * Create an instance of {@link WsIsBookingCancelable1XResponse }
     * 
     */
    public WsIsBookingCancelable1XResponse createWsIsBookingCancelable1XResponse() {
        return new WsIsBookingCancelable1XResponse();
    }

    /**
     * Create an instance of {@link WsConfirmBookingResponse }
     * 
     */
    public WsConfirmBookingResponse createWsConfirmBookingResponse() {
        return new WsConfirmBookingResponse();
    }

    /**
     * Create an instance of {@link WsCheckBookingResponse }
     * 
     */
    public WsCheckBookingResponse createWsCheckBookingResponse() {
        return new WsCheckBookingResponse();
    }

    /**
     * Create an instance of {@link WsGetCity }
     * 
     */
    public WsGetCity createWsGetCity() {
        return new WsGetCity();
    }

    /**
     * Create an instance of {@link WsSourceDestinationPair }
     * 
     */
    public WsSourceDestinationPair createWsSourceDestinationPair() {
        return new WsSourceDestinationPair();
    }

    /**
     * Create an instance of {@link WsGetSeatMapResponse }
     * 
     */
    public WsGetSeatMapResponse createWsGetSeatMapResponse() {
        return new WsGetSeatMapResponse();
    }

}
