//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:01:03 PM IST 
//


package com.travis.webservices.wsticketvala.wsticketvala;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.travis.webservices.WsCancelBooking1XRQ;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wsCancelBooking1XRQ" type="{http://travis.com/webservices}wsCancelBooking1XRQ" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wsCancelBooking1XRQ"
})
@XmlRootElement(name = "wsCancelBooking1X")
public class WsCancelBooking1X {

    protected WsCancelBooking1XRQ wsCancelBooking1XRQ;

    /**
     * Gets the value of the wsCancelBooking1XRQ property.
     * 
     * @return
     *     possible object is
     *     {@link WsCancelBooking1XRQ }
     *     
     */
    public WsCancelBooking1XRQ getWsCancelBooking1XRQ() {
        return wsCancelBooking1XRQ;
    }

    /**
     * Sets the value of the wsCancelBooking1XRQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsCancelBooking1XRQ }
     *     
     */
    public void setWsCancelBooking1XRQ(WsCancelBooking1XRQ value) {
        this.wsCancelBooking1XRQ = value;
    }

}
