//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 05:01:03 PM IST 
//


package com.travis.webservices.wsticketvala.wsticketvala;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.travis.webservices.WsConfirmBookingRS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wsConfirmBookingRS" type="{http://travis.com/webservices}wsConfirmBookingRS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wsConfirmBookingRS"
})
@XmlRootElement(name = "wsConfirmBookingResponse")
public class WsConfirmBookingResponse {

    protected WsConfirmBookingRS wsConfirmBookingRS;

    /**
     * Gets the value of the wsConfirmBookingRS property.
     * 
     * @return
     *     possible object is
     *     {@link WsConfirmBookingRS }
     *     
     */
    public WsConfirmBookingRS getWsConfirmBookingRS() {
        return wsConfirmBookingRS;
    }

    /**
     * Sets the value of the wsConfirmBookingRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsConfirmBookingRS }
     *     
     */
    public void setWsConfirmBookingRS(WsConfirmBookingRS value) {
        this.wsConfirmBookingRS = value;
    }

}
