//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.20 at 10:22:20 AM IST 
//


package com.mmt.car.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.makemytrip.carrental.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.makemytrip.carrental.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLocalCarListRequest }
     * 
     */
    public GetLocalCarListRequest createGetLocalCarListRequest() {
        return new GetLocalCarListRequest();
    }

    /**
     * Create an instance of {@link LocalInventoryRecheckRequest }
     * 
     */
    public LocalInventoryRecheckRequest createLocalInventoryRecheckRequest() {
        return new LocalInventoryRecheckRequest();
    }

    /**
     * Create an instance of {@link AmenityList }
     * 
     */
    public AmenityList createAmenityList() {
        return new AmenityList();
    }

    /**
     * Create an instance of {@link Amenity }
     * 
     */
    public Amenity createAmenity() {
        return new Amenity();
    }

    /**
     * Create an instance of {@link GetLocalCarListResponse }
     * 
     */
    public GetLocalCarListResponse createGetLocalCarListResponse() {
        return new GetLocalCarListResponse();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link GetOutstationCarListResponse }
     * 
     */
    public GetOutstationCarListResponse createGetOutstationCarListResponse() {
        return new GetOutstationCarListResponse();
    }

    /**
     * Create an instance of {@link OutstationInventoryRecheckRequest }
     * 
     */
    public OutstationInventoryRecheckRequest createOutstationInventoryRecheckRequest() {
        return new OutstationInventoryRecheckRequest();
    }

    /**
     * Create an instance of {@link ResultsList }
     * 
     */
    public ResultsList createResultsList() {
        return new ResultsList();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link GetOutstationCarListRequest }
     * 
     */
    public GetOutstationCarListRequest createGetOutstationCarListRequest() {
        return new GetOutstationCarListRequest();
    }

    /**
     * Create an instance of {@link SeatingCapacityList }
     * 
     */
    public SeatingCapacityList createSeatingCapacityList() {
        return new SeatingCapacityList();
    }

    /**
     * Create an instance of {@link OutstationInventoryRecheckResponse }
     * 
     */
    public OutstationInventoryRecheckResponse createOutstationInventoryRecheckResponse() {
        return new OutstationInventoryRecheckResponse();
    }

    /**
     * Create an instance of {@link LocalInventoryRecheckResponse }
     * 
     */
    public LocalInventoryRecheckResponse createLocalInventoryRecheckResponse() {
        return new LocalInventoryRecheckResponse();
    }

}
